# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-goodbye-world',
                'doc_host': 'https://reddesignsguy.github.io',
                'git_url': 'https://github.com/reddesignsguy/nbdev-goodbye-world',
                'lib_path': 'nbdev_goodbye_world'},
  'syms': {'nbdev_goodbye_world.core': {'nbdev_goodbye_world.core.foo': ('core.html#foo', 'nbdev_goodbye_world/core.py')}}}
